In [8]:
class Animal:
    isalive = True
    age = 0

In [9]:
my_cat = Animal()

In [10]:
print(my_cat)
print(type(my_cat))

<class '__main__.Animal'>


In [11]:
my_cat.isalive

True

In [12]:
my_second_cat = Animal()

In [13]:
my_cat.age == my_second_cat.age

True

In [14]:
my_cat.age = 2

In [15]:
my_cat.age == my_second_cat.age

False

In [16]:
Animal.isalive = False

In [17]:
print(my_cat.isalive)
print(my_second_cat.isalive)

False
False


In [18]:
Animal.isalive = True

In [19]:
class Cat:
    isalive = True
    age = 0
    sound = "meow"

    def __init__(self, location):
        self.location = location.values()

    def aged(self):
        self.age += 1

- packing and unpacking

In [20]:
fruits = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]

In [21]:
first, second, *remaning, last = fruits

In [22]:
print(first)
print(last)
print(second)

apple
mango
banana


In [23]:
print(remaning)

['cherry', 'orange', 'kiwi', 'melon']


In [24]:
def my_example(*args):
    return print(args)

In [25]:
my_example(1, 2, 3, 'a', 'b', 'c')

(1, 2, 3, 'a', 'b', 'c')


In [26]:
def my_example(my_number, *args):
    return f"My number is: {my_number}, {args}"

In [27]:
my_example(10, 11, 12)

'My number is: 10, (11, 12)'

In [28]:
def second_example(**kwargs):
    return kwargs

In [29]:
second_example(number_first_number=10, number_second_number=11,)

{'number_first_number': 10, 'number_second_number': 11}

In [30]:
def third_example(special_number=1, **kwargs):
    return f"Special number: {special_number}, Others: {kwargs}"

In [31]:
third_example(special_number=2, number_first_number=10, number_second_number=11,)

"Special number: 2, Others: {'number_first_number': 10, 'number_second_number': 11}"

In [32]:
# def my_function(<positional_args>, *args, <key-word_args>, **kwargs)

## Numpy

In [100]:
number = 15

In [101]:
type(number)

int

In [102]:
dir(number)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_count',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes

In [103]:
my_list = [1, 2, 3]

In [104]:
dir(my_list)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [105]:
# pip install numpy
# pip3 install numpy

In [ ]:
import numpy as np

In [107]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [108]:
array_a = np.array([1, 2, 3, 4])

In [109]:
array_a

array([1, 2, 3, 4])

In [110]:
array_b = np.array([0, .5, 1, 1.5, 2])

In [111]:
array_b

array([0. , 0.5, 1. , 1.5, 2. ])

In [112]:
array_a[0]

1

In [113]:
array_b[-1]

2.0

In [114]:
array_a[:2]

array([1, 2])

In [115]:
array_a.dtype

dtype('int64')

In [116]:
array_b.dtype

dtype('float64')

In [117]:
empty_array = np.array([])

In [118]:
empty_array.dtype

dtype('float64')

In [119]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [120]:
np.array(['veri', 'bilimi'])

array(['veri', 'bilimi'], dtype='<U6')

In [121]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [122]:
array_a.shape

(4,)

In [123]:
my_array.shape

(2, 3)

In [124]:
array_a.ndim

1

In [125]:
my_array.ndim

2

In [126]:
my_array.size

6

In [127]:
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 6],
        [3, 2, 1]
    ]
])

In [128]:
my_array.ndim

3

In [129]:
my_array.shape

(2, 2, 3)

In [130]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]    
])

In [131]:
my_array[1]

array([4, 5, 6])

In [132]:
my_array[1][0]

4

In [133]:
my_array[1, 0]

4

In [134]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [136]:
my_array[1] = np.array([10, 10, 10])

In [137]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [138]:
my_array[2] = 99

In [139]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [140]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [141]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
my_array.reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [143]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [144]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [145]:
np.ones((2, 5, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [146]:
my_array = np.random.random((5,2))

In [147]:
my_array

array([[0.60718764, 0.86505436],
       [0.64541542, 0.02096717],
       [0.7212495 , 0.13936395],
       [0.82467528, 0.70648366],
       [0.03726706, 0.92660088]])

In [148]:
np.linspace(5, 10, 5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [149]:
# any(), all(), full(), concatenate()

In [150]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [151]:
array1 = array1.reshape(2, 5)

In [152]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [153]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [154]:
array1.sum()

45

In [155]:
array1.mean()

4.5

In [156]:
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [157]:
array1.sum(axis=1)

array([10, 35])

In [158]:
array1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [159]:
array1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [160]:
array1 += 10
array1

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

- boolean arrays

In [161]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [163]:
a[0], a[-1]

(0, 3)

In [162]:
a[[0, -1]]

array([0, 3])

In [164]:
a[[True, False, False, True]]

array([0, 3])

In [165]:
a >= 2 

array([False, False,  True,  True])

In [166]:
a[a >= 2]

array([2, 3])

In [167]:
a[a > a.mean()]

array([2, 3])

In [170]:
a[(a == 0) | (a == 1)] # instead of and, or, not we will use &|~

array([0, 1])

In [171]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

- 100'e kadar rastgele tamsayılardan oluşan, 3,3 bir matris oluşturun.
- 30'dan büyük olanları boolean yöntemi ile filtreleyin.

In [174]:
rand_array = np.random.randint(100, size=(3,3))

In [175]:
rand_array

array([[71, 26, 21],
       [82, 85, 77],
       [34, 40, 81]])

In [177]:
boolean_array = rand_array > 30

In [178]:
boolean_array

array([[ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [180]:
rand_array[boolean_array]

array([71, 82, 85, 77, 34, 40, 81])

In [181]:
rand_array[rand_array > 30]

array([71, 82, 85, 77, 34, 40, 81])

In [182]:
import sys

In [183]:
sys.getsizeof(10)

28

In [184]:
sys.getsizeof(1000**100)

160

In [185]:
np.dtype(int).itemsize

8

In [186]:
np.dtype(np.int8).itemsize

1

In [187]:
my_list = list(range(1000000))

In [188]:
my_array = np.arange(1000000)

In [191]:
%time np.sum(my_array ** 2)

CPU times: user 2.32 ms, sys: 0 ns, total: 2.32 ms
Wall time: 1.56 ms


333332833333500000

In [192]:
%time sum([number ** 2 for number in my_list])

CPU times: user 177 ms, sys: 13.3 ms, total: 191 ms
Wall time: 190 ms


333332833333500000